//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name TellFortuneResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TellFortune", ReplyAction="*")]
        ConsoleApp1.ServiceReference1.TellFortuneResponse TellFortune(ConsoleApp1.ServiceReference1.TellFortuneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TellFortune", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.TellFortuneResponse> TellFortuneAsync(ConsoleApp1.ServiceReference1.TellFortuneRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TellFortuneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TellFortune", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ServiceReference1.TellFortuneRequestBody Body;
        
        public TellFortuneRequest() {
        }
        
        public TellFortuneRequest(ConsoleApp1.ServiceReference1.TellFortuneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TellFortuneRequestBody {
        
        public TellFortuneRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TellFortuneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TellFortuneResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ServiceReference1.TellFortuneResponseBody Body;
        
        public TellFortuneResponse() {
        }
        
        public TellFortuneResponse(ConsoleApp1.ServiceReference1.TellFortuneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TellFortuneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TellFortuneResult;
        
        public TellFortuneResponseBody() {
        }
        
        public TellFortuneResponseBody(string TellFortuneResult) {
            this.TellFortuneResult = TellFortuneResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsoleApp1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReference1.WebService1Soap>, ConsoleApp1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ServiceReference1.TellFortuneResponse ConsoleApp1.ServiceReference1.WebService1Soap.TellFortune(ConsoleApp1.ServiceReference1.TellFortuneRequest request) {
            return base.Channel.TellFortune(request);
        }
        
        public string TellFortune() {
            ConsoleApp1.ServiceReference1.TellFortuneRequest inValue = new ConsoleApp1.ServiceReference1.TellFortuneRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.TellFortuneRequestBody();
            ConsoleApp1.ServiceReference1.TellFortuneResponse retVal = ((ConsoleApp1.ServiceReference1.WebService1Soap)(this)).TellFortune(inValue);
            return retVal.Body.TellFortuneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.TellFortuneResponse> ConsoleApp1.ServiceReference1.WebService1Soap.TellFortuneAsync(ConsoleApp1.ServiceReference1.TellFortuneRequest request) {
            return base.Channel.TellFortuneAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.TellFortuneResponse> TellFortuneAsync() {
            ConsoleApp1.ServiceReference1.TellFortuneRequest inValue = new ConsoleApp1.ServiceReference1.TellFortuneRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.TellFortuneRequestBody();
            return ((ConsoleApp1.ServiceReference1.WebService1Soap)(this)).TellFortuneAsync(inValue);
        }
    }
}
